[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
usdx_bridge = "G4vzRkbX5D2Ja2RJTMKbn5TVHXKLaoi57zhdiBReSEMr"

[programs.devnet]
usdx_bridge = "G4vzRkbX5D2Ja2RJTMKbn5TVHXKLaoi57zhdiBReSEMr"

[programs.mainnet]
usdx_bridge = "G4vzRkbX5D2Ja2RJTMKbn5TVHXKLaoi57zhdiBReSEMr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
